/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-08-05 19:23:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.init;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Pagetitle -->\r\n");
      out.write("<!-- <h1 class=\"pagetitle\">Loggin</h1> -->\r\n");
      out.write("\r\n");
      out.write("<!-- Content unit - One column -->\r\n");
      out.write("<!-- <h1 class=\"block\">1 - Configuration form</h1> -->\r\n");
      out.write("<div class=\"column1-unit\">\r\n");
      out.write("\t<div class=\"contactform\">\r\n");
      out.write("\t\t<form name=\"f\" action=\"/Template/j_spring_security_check\" method=\"post\">\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend>&nbsp;Loggin&nbsp;</legend>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label for=\"contact_title\" class=\"left\">Usuario:</label> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"j_username\" id=\"j_username\" class=\"field\" value=\"\" tabindex=\"1\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label for=\"contact_firstname\" class=\"left\">Contraseña:</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"j_password\" id=\"j_password\" class=\"field\" value=\"\" tabindex=\"1\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("<!-- \t\t\t\t<p> -->\r\n");
      out.write("<!-- \t\t\t\t\t<td>Remember me on this computer.</td> -->\r\n");
      out.write("<!-- \t\t\t\t\t<input type=\"checkbox\" name=\"_spring_security_remember_me\"class=\"button\" /> -->\r\n");
      out.write("<!-- \t\t\t\t</p> -->\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"submit\" id=\"submit\" class=\"button\" value=\"Login\" tabindex=\"6\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
